-- Migration 0018 changed person.role's DEFAULT from 'adult' to 'member' but
-- left the existing rows alone. Every instance created before 0.3.0 therefore
-- holds role = 'adult' — the old default, which the setup wizard never
-- overrode — and 'adult' is neither 'admin' nor 'member'. On upgrade that
-- leaves requireAdmin() rejecting everybody and the administration controls
-- absent from the page, with the README's psql one-liner as the only way back.
--
-- Every legacy row becomes an administrator, not just the first. Before 0.3.0
-- there were no roles: anyone who could sign in could do anything on the
-- instance. Promoting all of them preserves exactly that, so an upgrade takes
-- nothing away from anyone; demoting the household afterwards is one click per
-- person and is theirs to decide. Guessing which single row "really" owns the
-- box would silently strip capability from whoever guessed wrong.
--
-- Written as its own migration rather than as a line added to 0018 because
-- Drizzle applies migrations by timestamp and never re-checks the stored hash:
-- editing 0018 in place would be a silent no-op on every database that has
-- already run it. The predicate is a set difference rather than = 'adult' so
-- re-running this can only ever be a no-op on a correct database.
UPDATE "person" SET "role" = 'admin' WHERE "role" NOT IN ('admin', 'member');
