-- tenancy.tenant_contact was one free-text string: a phone number, or a name and
-- a phone number, or an email, or all three run together. It becomes a real
-- contact row, linked to the tenancy it came from.
--
-- The original text is preserved VERBATIM in notes rather than parsed into phone
-- and email columns. A parser would be guessing at the shape of text nobody
-- wrote to a format, and a wrong guess here silently loses the only way to reach
-- a tenant. Splitting it out is a job for a person looking at the contact, and
-- the notes field is where they will find what was there.

-- AS MATERIALIZED states a requirement this migration depends on: `seed` must be
-- evaluated exactly ONCE. gen_random_uuid() is volatile, so a re-evaluated CTE
-- would hand the two inserts different uuids, and every link row would point at
-- a contact that was never inserted.
--
-- PostgreSQL would materialize here anyway — it declines to inline a CTE that is
-- referenced more than once, and declines again for one containing a volatile
-- function, and both are true of `seed`. Measured: removing the keyword does not
-- change the result. It is kept because the requirement should be written down
-- rather than deduced from two inlining rules that a future rewrite (dropping
-- the second reference, say) could quietly stop satisfying.
with seed as materialized (
	select
		t.id            as tenancy_id,
		gen_random_uuid()::text as contact_id,
		t.tenant_name   as tenant_name,
		t.tenant_contact as tenant_contact
	from tenancy t
	where coalesce(trim(t.tenant_contact), '') <> ''
),
inserted as (
	insert into contact (id, name, notes, created_at, updated_at)
	select contact_id, tenant_name, tenant_contact, now(), now()
	from seed
	returning id
)
insert into contact_tenancy (contact_id, tenancy_id)
select contact_id, tenancy_id from seed;
--> statement-breakpoint

-- Generated by drizzle-kit from the schema change. It must come AFTER the
-- statement above: dropping the column first would throw the contact text away
-- before anything had read it.
ALTER TABLE "tenancy" DROP COLUMN "tenant_contact";
